server:
  port: 8090
spring:
  mvc:
    static-path-pattern: /static/**
  mail:
    host: smtp.sina.com
    username: gk2018bingo@sina.com
    password: 2989ce3b3c5c9f4a
    default-encoding: utf-8
  datasource:
    #    url: jdbc:mysql://39.107.205.151:3306/fwwb_dataset?useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
#    url: jdbc:mysql://127.0.0.1:3306/demo?useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
#    username: root
#    #输入自己的账户密码
#    password: 78089091
#      url: jdbc:mysql://127.0.0.1:3306/demo?useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
#      username: root
#      #输入自己的账户密码
#      password: 78089091
    url: jdbc:mysql://rm-bp1ef7p1kjz58v31fzo.mysql.rds.aliyuncs.com:3306/db123?useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: tzy
    #输入自己的账户密码
    password: 990223tzyTZY
    driver-class-name: com.mysql.cj.jdbc.Driver
  web:
    resources:
      static-locations: classpath:/static/


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.bjtu.questionPlatform.entity
logging:
#  config:  F:\new\questionPlatform\questionPlatform_back_end\src\main\resources\log4j2-spring.xml
  config: ./src/main/resources/log4j2-spring.xml
  level:
    cn.jay.repository: trace

jwt:
  header: token
  secret: CodingLiOOT
  expiration: 2400000

encode:
  secret: CodingLiOOT
mail:
  fromMail:
    addr: gk2018bingo@sina.com
    subject: 主题：邮件验证码